FROM localhost/base_frontend_1:latest
WORKDIR /workdir/
#COPY requirements.txt /workdir/frontend/requirements.txt
RUN /env/bin/pip3 install -r /workdir/frontend/requirements.txt

RUN /env/bin/pip3 freeze
#COPY . /workdir/.
##RUN ls -R /workdir/
CMD ["gunicorn"  , "--bind", "0.0.0.0:8002", "/workdir/frontend/wsgi:application"]
