FROM localhost/base_frontend_1:latest
WORKDIR /workdir/dashapps
COPY requirements.txt /env/requirements.txt
RUN /env/bin/pip3 install -r /env/requirements.txt

RUN /env/bin/pip3 freeze
#COPY . /workdir/.
##RUN ls -R /workdir/
CMD ["gunicorn"  , "--bind", "0.0.0.0:8006", "wsgi:application"]
