podman start infra_main_backend
podman start container_mariadb
podman start container_redis_1
podman start container_fastapi_about_1
podman start container_fastapi_data_1
podman start container_application_1



