version: '3'

# docker build -t jupyterhub_dockerfile:0.1 .

#docker run --rm -it --user jupyterhub 
#--network jupyterhub -v /var/run/docker.sock:/var/run/docker.sock
#--name jupyterhub_dockerfile
# -p 8000:8000 jupyterhub_dockerfile:0.1

services:
  jupyterhub:
    build: .
    image: jupyterhub_dockerfile
    container_name: jupyterhub_dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- jupyterhub_data:/srv/jupyterhub/env/share/jupyterhub
    environment:
      - DOCKER_NETWORK_NAME=jupyterhub
      - HUB_IP=jupyterhub
      #- HOST
    ports:
      - "8000:8000"
    restart: on-failure
